name: Verify Build Package
description: "Check the built package and its metadata"

runs:
  using: "composite"
  steps:
    - name: Check build with twine
      shell: bash
      run: |
        uv pip install twine
        twine check dist/*

    - name: Check package metadata
      shell: bash
      run: |
        dev/package/check_metadata.sh

    - name: Check dependency tree
      shell: bash
      run: |
        dev/package/check_dependency_tree.sh

    - name: Check package import
      shell: bash
      run: |
        python -c "import objectory; print(objectory.__version__)"

    - name: Check that pyright recognizes the package as typed
      shell: bash
      run: |
        uv pip install pyright
        dev/package/check_type.sh
