name: "Setup Python environment"
description: "Checkout code and install dependencies"

inputs:
  python-version:
    default: "3.13"
    description: "Python version to use"
    required: false
    type: string
  package-name:
    default: ""
    description: "Optional package name to install"
    required: false
    type: string
  package-version:
    default: ""
    description: "Optional package version to install"
    required: false
    type: string
  install-optional-deps:
    default: true
    description: "Whether to install the optional dependencies"
    required: false
    type: boolean
  install-docs-deps:
    default: false
    description: "Whether to install the dependencies to generate docs"
    required: false
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Set environment variable
      shell: bash
      run: |
        echo $(poetry run poetry env info --path)/bin >> $GITHUB_PATH

    - name: Install required packages
      if: ${{ !inputs.install-optional-deps }}
      shell: bash
      run: |
        make install

    - name: Install all packages
      if: ${{ inputs.install-optional-deps }}
      shell: bash
      run: |
        make install-all

    - name: Install valid package version
      if: ${{ inputs.package-name != '' }}
      uses: durandtibo/pip-install-package-action@v0.4.0
      with:
        package-name: ${{ inputs.package-name }}
        package-version: ${{ matrix.package-version }}
        python-version: ${{ matrix.python-version }}

    - name: Show installed packages
      shell: bash
      run: |
        poetry show
        poetry show --tree
