site_name: objectory
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - get_started.md
  - User Guide:
      - name_resolution.md
  - GitHub: https://github.com/durandtibo/objectory

repo_url: https://github.com/durandtibo/objectory
repo_name: durandtibo/objectory

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings

extra:
  version:
    method: mike

copyright: Copyright &copy; 2022 - present Thibaut Durand
